### ISSUE TITLE
Implement an overload to accept an Enum value

### ISSUE THREAD

**Issue by InteXX** [zspitz/ExpressionTreeToString#26]
The so-called "Magic String" problem can be avoided with an additional overload for the `ToString()` extension method that accepts an `Enum` argument instead of a `String`.

This enhancement need not interfere with existing architecture; it can simply call an existing overload.

Here's an example implementation:

    Imports System.Runtime.CompilerServices
    Imports System.Linq.Expressions
    Imports System.ComponentModel
    Imports System.Reflection

    Namespace ExpressionTreeToString
      Public Module ExpressionExtension
        <Extension>
        Public Function ToString(expr As Expression, formatter As Formatters, Optional language As String = "Formatter default") As String
          Return expr.ToString(formatter.ToDescription, language)
        End Function

        <Extension>
        Public Function ToDescription(Of T)(Value As T) As String
          Dim aAttributes As DescriptionAttribute()
          Dim oInfo As FieldInfo

          oInfo = Value.GetType.GetField(Value.ToString)

          If oInfo Is Nothing Then
            Throw New ArgumentOutOfRangeException($"Value {Value.ToString} not found in {Value.GetType.ToString}")
          Else
            aAttributes = oInfo.GetCustomAttributes(GetType(DescriptionAttribute), False)

            If aAttributes.Length = 0 Then
              ToDescription = Value.ToString
            Else
              ToDescription = aAttributes.First.Description
            End If
          End If
        End Function
      End Module

      Public Enum Formatters
        <Description(FormatterNames.CSharp)> CSharp
        <Description(FormatterNames.VisualBasic)> VisualBasic
        <Description(FormatterNames.FactoryMethods)> FactoryMethods
        <Description(FormatterNames.ObjectNotation)> ObjectNotation
        <Description(FormatterNames.TextualTree)> TextualTree
      End Enum
    End Namespace

**Comment by zspitz** [comment]
This is now fixed. I'm leaving the issue open because I still have to update the README and the wiki.

**Comment by zspitz** [comment]
Wiki has been updated [here](https://github.com/zspitz/ExpressionTreeToString/wiki/Available-renderers) and [here](https://github.com/zspitz/ExpressionTreeToString/wiki#tostring-extension-methods).
